# Generated by Django 5.0.6 on 2024-07-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photos/default_photo.jpg', upload_to='photos/'),
        ),
    ]
